name: general
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  super-linter:
    name: super-linter
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run super linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: "true"
          VALIDATE_BASH: "true"
          VALIDATE_EDITORCONFIG: "true"
          VALIDATE_MD: "true"
          VALIDATE_YAML: "true"
          FILTER_REGEX_EXCLUDE: '.*/(CHANGELOG\.md)'

  textidote:
    name: textidote
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run textidote
        uses: ChiefGokhlayeh/textidote-action@v4
        id: textidote-main
        with:
          working_directory: .
          root_file: src/resume.tex
          report_type: plain
          report_file: ""
      - name: Run textidote to generate report
        uses: ChiefGokhlayeh/textidote-action@v4
        with:
          working_directory: .
          root_file: src/resume.tex
          report_type: html
          report_file: report.html
      - name: Upload textidote report
        uses: actions/upload-artifact@v2
        with:
            name: textidote_report
            path: report.html
            if-no-files-found: error
      - name: Assert num_warnings == 0
        if: ${{ steps.textidote-main.outputs.num_warnings != 0 }}
        run: 'echo "num_warnings: ${{ steps.textidote-main.outputs.num_warnings }}"; exit 1;'

  build-latex:
    name: build-latex
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile latex documents
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: src
          root_file: resume.tex
          latexmk_use_lualatex: true
      - name: Upload resume.pdf
        uses: actions/upload-artifact@v2
        with:
            name: resume
            path: src/resume.pdf
            if-no-files-found: error

  release:
    name: release
    if: github.ref == 'refs/heads/main'
    needs:
      - super-linter
      - textidote
      - build-latex
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Download resume.pdf from build-latex
        uses: actions/download-artifact@v2
        with:
          name: resume
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: kirintwn
          GIT_AUTHOR_EMAIL: cy91244@gmail.com
          GIT_COMMITTER_NAME: kirintwn
          GIT_COMMITTER_EMAIL: cy91244@gmail.com
        run: |
            npx \
              -p @semantic-release/commit-analyzer \
              -p @semantic-release/release-notes-generator \
              -p conventional-changelog-conventionalcommits \
              -p @semantic-release/changelog \
              -p @semantic-release/git \
              -p @semantic-release/github \
              -p semantic-release \
              semantic-release

  deploy-gh-pages:
    name: deploy-gh-pages
    if: github.ref == 'refs/heads/main'
    needs:
      - release
    runs-on: ubuntu-20.04
    steps:
      - name: Download resume.pdf from build-latex
        uses: actions/download-artifact@v2
        with:
          name: resume
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          force_orphan: true
          commit_message: 'release: update gh-pages to latest version'
